---
- hosts: docker
  tasks:

    - name: Instal docker module
      ansible.builtin.command: sudo pip3 install docker

    - name: Create a volume for the web Container
      community.docker.docker_volume:
        name: bgapp-web-vol

    - name: Create a network for bgapp
      community.docker.docker_network:
        name: bgapp-net

    - name: Run Web Container
      community.docker.docker_container:
        name: web
        image: merev/bgapp-web-component
        ports:
          -  "8080:80"
        networks:
          - name: bgapp-net
        volumes:
          - bgapp-web-vol:/var/www/html
